[build]
  publish = "dist"
  command = "corepack enable && pnpm install --frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "20"
  ROLLUP_SKIP_NODEJS_NATIVE = "1"
  ROLLUP_USE_NODEJS = "1"
  NPM_FLAGS = "--version" # This helps Netlify auto-detect pnpm
  PNPM_VERSION = "10"